// ===== SCORING A WEEK =====
// Turning NFL results into league results: picked a loser and you survive,
// picked a winner or a tie and the case closes on you, and if the last game of
// the week kicks off with nothing filed, it closes anyway.
//
// SAFE TO RUN OVER AND OVER
// That is the point of it. Press it every day of the week if you like: games
// that have not finished are left alone and reported as pending, a result that
// is already written is written again to the same value, and somebody already
// marked as never having filed is not marked twice.
//
// Until this existed there was no process. Nothing on the site ever wrote
// SURVIVED or DUN DUN - every reference to them in js/ reads - so a week was
// scored by opening the Supabase table editor and typing thirty rows by hand.
//
// WHERE THE RESULTS COME FROM
// js/nfl-scores.js, regenerated by tools/update-nfl-scores.mjs from the same
// Plain Text Sports page the schedule is built from. The database is told the
// outcome rather than asked to go and find it: a Postgres function has no
// business making an outbound call to a scoreboard, and this way the admin sees
// exactly what is about to be written before any of it is.
//
// NOTHING IS WRITTEN WITHOUT A LOOK FIRST
// Preview and commit are the same call to _2026_admin_score_week with one
// argument flipped, so what the preview shows is what the commit does - not a
// second implementation that might disagree with it.
(function () {
  const SCORE_CONFIG = window.FF_SUPABASE_CONFIG || {};
  const SCORE_RPC = SCORE_CONFIG.rpcs?.adminScoreWeek || '_2026_admin_score_week';
  const TOTAL_WEEKS = 18;

  let previewedWeek = 0;

  const els = {};

  const scoreDb = window.ffAuthClient?.auth ? window.ffAuthClient : null;

  document.addEventListener('DOMContentLoaded', () => {
    els.panel = document.getElementById('adminScorePanel');
    els.week = document.getElementById('adminScoreWeek');
    els.games = document.getElementById('adminScoreGames');
    els.preview = document.getElementById('btnPreviewScore');
    els.commit = document.getElementById('btnCommitScore');
    els.report = document.getElementById('adminScoreReport');
    if (!els.week) return;

    for (let week = 1; week <= TOTAL_WEEKS; week += 1) {
      const option = document.createElement('option');
      option.value = String(week);
      option.textContent = `Week ${week}`;
      els.week.appendChild(option);
    }
    els.week.value = String(Number(window.CURRENT_WEEK) || 1);

    els.week.addEventListener('change', () => {
      // A preview belongs to the week it was taken of.
      previewedWeek = 0;
      els.commit.disabled = true;
      els.report.innerHTML = '';
      describeWeek();
    });

    els.preview.addEventListener('click', () => run(false));
    els.commit.addEventListener('click', () => run(true));

    describeWeek();
  });

  function selectedWeek() {
    return Number(els.week?.value) || 1;
  }

  // Every team in a finished game, and what happened to it. Two entries per
  // game, because a pick names one side.
  function finalsForWeek(week) {
    const games = window.NFL_SCORE_HELPERS?.getWeekScores?.(week) || [];
    const outcomeFor = window.NFL_SCORE_HELPERS?.getTeamResultFromGame;
    if (!outcomeFor) return [];

    const finals = [];
    for (const game of games) {
      if (!game.final) continue;
      for (const team of [game.away, game.home]) {
        const outcome = outcomeFor(game, team);
        if (outcome) finals.push({ team, outcome });
      }
    }
    return finals;
  }

  function scheduledCount(week) {
    const games = window.NFL_SCHEDULE_GAMES || [];
    return games.filter((game) => Number(game.week) === Number(week)).length;
  }

  function finalCount(week) {
    return (window.NFL_SCORE_HELPERS?.getWeekScores?.(week) || [])
      .filter((game) => game.final).length;
  }

  // Picks lock five minutes before their own team's game, so once the last game
  // of the week has kicked off there is no way left to file one. That, and not
  // the last final, is the moment a missing pick becomes an elimination -
  // waiting for the game to end would just be waiting.
  //
  // A week still carrying a game with no kickoff time cannot be judged, so it is
  // treated as open. Weeks 16 and 17 have those until the schedule is
  // regenerated.
  function picksClosed(week, now = Date.now()) {
    const games = (window.NFL_SCHEDULE_GAMES || [])
      .filter((game) => Number(game.week) === Number(week));
    if (!games.length) return false;

    const kickoffs = games.map((game) => Date.parse(game.kickoffUtc || ''));
    if (kickoffs.some((stamp) => !Number.isFinite(stamp))) return false;

    return now >= Math.max(...kickoffs);
  }

  function describeWeek() {
    if (!els.games) return;

    const week = selectedWeek();
    const scheduled = scheduledCount(week);
    const finals = finalCount(week);

    if (!scheduled) {
      els.games.textContent = 'No games on the schedule for that week.';
      return;
    }

    els.games.textContent = picksClosed(week)
      ? `${finals} of ${scheduled} final. Picks are closed for the week, so anyone who never filed is out.`
      : `${finals} of ${scheduled} final. Picks are still open, so nobody is out for a missing one yet.`;
  }

  async function run(commit) {
    if (!scoreDb) return;

    const week = selectedWeek();

    if (commit && previewedWeek !== week) {
      window.ffToast?.('Preview it first.', 'note', 'score');
      return;
    }

    const finals = finalsForWeek(week);

    // Nothing final and nothing closed means there is genuinely nothing to do.
    // Said rather than sent, because running this every day of the week is the
    // expected way to use it and a no-op should not look like a failure.
    if (!finals.length && !picksClosed(week)) {
      window.ffToast?.(
        `No final scores on file for Week ${week} yet. Run tools/update-nfl-scores.mjs and deploy.`,
        'note', 'score');
      return;
    }

    els.preview.disabled = true;
    els.commit.disabled = true;

    const { data, error } = await scoreDb.rpc(SCORE_RPC, {
      p_week: week,
      p_finals: finals,
      p_picks_closed: picksClosed(week),
      p_commit: Boolean(commit)
    });

    els.preview.disabled = false;

    if (error) {
      const missing = error.code === 'PGRST202' ||
        /could not find the function|does not exist/i.test(error.message || '');
      window.ffToast?.(
        missing
          ? 'Scoring is not switched on yet: run supabase/sql/ff_score_week.sql.'
          : `Scoring failed: ${error.message}`,
        'bad', 'score');
      console.error('_2026_admin_score_week failed:', error);
      return;
    }

    renderReport(data, commit);

    if (commit) {
      previewedWeek = 0;
      const written = (data.survived?.length || 0) + (data.dun_dun?.length || 0) +
        (data.no_pick?.length || 0);
      window.ffToast?.(`Week ${week} scored. ${written} record${written === 1 ? '' : 's'} written.`,
        'good', 'score');
      // The roster's pick counts and everything else on the page are now stale.
      window.dispatchEvent(new CustomEvent('ff-auth-changed', { detail: { user: null, profile: null } }));
    } else {
      previewedWeek = week;
      els.commit.disabled = false;
      window.ffToast?.('Nothing written yet. Check it, then Score The Week.', 'note', 'score');
    }
  }

  function renderReport(data, committed) {
    const groups = [
      ['Survived', data.survived, 'good'],
      ['Dun Dun', data.dun_dun, 'bad'],
      ['Never filed', data.no_pick, 'bad'],
      ['Not final yet', data.pending, 'note']
    ];

    els.report.innerHTML = `
      <p class="admin-score-headline">${committed ? 'Written' : 'Would write'} for Week ${Number(data.week)}:</p>
      ${groups.map(([label, rows, kind]) => `
        <div class="admin-score-group admin-score-group-${kind}">
          <span class="admin-score-label">${escapeHtml(label)}</span>
          <span class="admin-score-count">${(rows || []).length}</span>
          <span class="admin-score-names">${(rows || []).map(nameOf).join(', ') || '-'}</span>
        </div>`).join('')}
    `;
  }

  function nameOf(row) {
    const name = escapeHtml(row.username || '(unknown)');
    return row.team ? `${name} (${escapeHtml(row.team)})` : name;
  }

  function escapeHtml(value) {
    return String(value == null ? '' : value)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;');
  }
})();
