// The 32 victims: NFL abbreviation (used for the logo URL) and team colours.
// Shared by the game (app.js) and the victims page (victims.js).
const NFL_TEAMS = [
  { name: "Arizona Cardinals",    abbr: "ARI", conference: "NFC", division: "West", primary: "#97233F", secondary: "#FFB612" },
  { name: "Atlanta Falcons",      abbr: "ATL", conference: "NFC", division: "South", primary: "#A71930", secondary: "#000000" },
  { name: "Baltimore Ravens",     abbr: "BAL", conference: "AFC", division: "North", primary: "#241773", secondary: "#9E7C0C" },
  { name: "Buffalo Bills",        abbr: "BUF", conference: "AFC", division: "East", primary: "#00338D", secondary: "#C60C30" },
  { name: "Carolina Panthers",    abbr: "CAR", conference: "NFC", division: "South", primary: "#0085CA", secondary: "#BFC0BF" },
  { name: "Chicago Bears",        abbr: "CHI", conference: "NFC", division: "North", primary: "#0B162A", secondary: "#C83803" },
  { name: "Cincinnati Bengals",   abbr: "CIN", conference: "AFC", division: "North", primary: "#FB4F14", secondary: "#000000" },
  { name: "Cleveland Browns",     abbr: "CLE", conference: "AFC", division: "North", primary: "#311D00", secondary: "#FF3C00" },
  { name: "Dallas Cowboys",       abbr: "DAL", conference: "NFC", division: "East", primary: "#003594", secondary: "#869397" },
  { name: "Denver Broncos",       abbr: "DEN", conference: "AFC", division: "West", primary: "#FB4F14", secondary: "#002244" },
  { name: "Detroit Lions",        abbr: "DET", conference: "NFC", division: "North", primary: "#0076B6", secondary: "#B0B7BC" },
  { name: "Green Bay Packers",    abbr: "GB", conference: "NFC", division: "North", primary: "#203731", secondary: "#FFB612" },
  { name: "Houston Texans",       abbr: "HOU", conference: "AFC", division: "South", primary: "#03202F", secondary: "#A71930" },
  { name: "Indianapolis Colts",   abbr: "IND", conference: "AFC", division: "South", primary: "#002C5F", secondary: "#A5ACAF" },
  { name: "Jacksonville Jaguars", abbr: "JAX", conference: "AFC", division: "South", primary: "#101820", secondary: "#D7A22A" },
  { name: "Kansas City Chiefs",   abbr: "KC", conference: "AFC", division: "West", primary: "#E31837", secondary: "#FFB81C" },
  { name: "Las Vegas Raiders",    abbr: "LV", conference: "AFC", division: "West", primary: "#000000", secondary: "#A5ACAF" },
  { name: "Los Angeles Chargers", abbr: "LAC", conference: "AFC", division: "West", primary: "#0080C6", secondary: "#FFC20E" },
  { name: "Los Angeles Rams",     abbr: "LAR", conference: "NFC", division: "West", primary: "#003594", secondary: "#FFA300" },
  { name: "Miami Dolphins",       abbr: "MIA", conference: "AFC", division: "East", primary: "#008E97", secondary: "#FC4C02" },
  { name: "Minnesota Vikings",    abbr: "MIN", conference: "NFC", division: "North", primary: "#4F2683", secondary: "#FFC62F" },
  { name: "New England Patriots", abbr: "NE", conference: "AFC", division: "East", primary: "#002244", secondary: "#C60C30" },
  { name: "New Orleans Saints",   abbr: "NO", conference: "NFC", division: "South", primary: "#101820", secondary: "#D3BC8D" },
  { name: "New York Giants",      abbr: "NYG", conference: "NFC", division: "East", primary: "#0B2265", secondary: "#A71930" },
  { name: "New York Jets",        abbr: "NYJ", conference: "AFC", division: "East", primary: "#FFFFFF", secondary: "#125740" },
  { name: "Philadelphia Eagles",  abbr: "PHI", conference: "NFC", division: "East", primary: "#004C54", secondary: "#A5ACAF" },
  { name: "Pittsburgh Steelers",  abbr: "PIT", conference: "AFC", division: "North", primary: "#FFB612", secondary: "#101820" },
  { name: "San Francisco 49ers",  abbr: "SF", conference: "NFC", division: "West", primary: "#AA0000", secondary: "#B3995D" },
  { name: "Seattle Seahawks",     abbr: "SEA", conference: "NFC", division: "West", primary: "#002244", secondary: "#69BE28" },
  { name: "Tampa Bay Buccaneers", abbr: "TB", conference: "NFC", division: "South", primary: "#D50A0A", secondary: "#FF7900" },
  { name: "Tennessee Titans",     abbr: "TEN", conference: "AFC", division: "South", primary: "#0C2340", secondary: "#4B92DB" },
  { name: "Washington Commanders",abbr: "WAS", conference: "NFC", division: "East", primary: "#5A1414", secondary: "#FFB612" }
];
