-- Generated from https://plaintextsports.com/nfl/2026/schedule
-- Fetched: 2026-08-11T22:10:51.656Z

create table if not exists public.ff_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  email text,
  first_name text,
  last_name text,
  avatar_data_url text,
  created_at timestamptz not null default now()
);

alter table public.ff_profiles
  add column if not exists email text,
  add column if not exists first_name text,
  add column if not exists last_name text,
  add column if not exists avatar_data_url text,
  add column if not exists created_at timestamptz not null default now();

create table if not exists public.ff_picks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  week integer not null check (week between 1 and 18),
  team text not null,
  username text,
  result text not null default 'SUSPECT',
  created_at timestamptz not null default now()
);

alter table public.ff_picks
  add column if not exists username text,
  add column if not exists result text not null default 'SUSPECT',
  add column if not exists created_at timestamptz not null default now();

create table if not exists public.ff_nfl_schedule (
  season integer not null,
  week integer not null check (week between 1 and 18),
  team text not null,
  opponent text not null,
  home_away text not null check (home_away in ('vs', '@')),
  kickoff_at_utc timestamptz null,
  is_tbd boolean not null default false,
  source_url text not null,
  primary key (season, week, team)
);

alter table public.ff_picks
  add column if not exists season integer not null default 2026,
  add column if not exists submitted_at_utc timestamptz not null default now(),
  add column if not exists opponent text,
  add column if not exists home_away text check (home_away in ('vs', '@')),
  add column if not exists kickoff_at_utc timestamptz,
  add column if not exists schedule_source_url text;

-- Pick changes are preserved as new rows, so old one-pick-per-week constraints must go.
do $$
declare
  constraint_row record;
begin
  for constraint_row in
    select con.conname as constraint_name
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace nsp on nsp.oid = rel.relnamespace
    join lateral unnest(con.conkey) with ordinality as cols(attnum, ord) on true
    join pg_attribute att on att.attrelid = rel.oid and att.attnum = cols.attnum
    where nsp.nspname = 'public'
      and rel.relname = 'ff_picks'
      and con.contype = 'u'
    group by con.conname
    having bool_or(att.attname = 'user_id')
      and (bool_or(att.attname = 'week') or bool_or(att.attname = 'team'))
  loop
    execute format('alter table public.ff_picks drop constraint if exists %I', constraint_row.constraint_name);
  end loop;
end $$;

truncate table public.ff_nfl_schedule;

insert into public.ff_nfl_schedule
  (season, week, team, opponent, home_away, kickoff_at_utc, is_tbd, source_url)
values
  (2026, 1, 'New England Patriots', 'Seattle Seahawks', '@', '2026-09-10T00:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week1'),
  (2026, 1, 'Seattle Seahawks', 'New England Patriots', 'vs', '2026-09-10T00:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week1'),
  (2026, 1, 'San Francisco 49ers', 'Los Angeles Rams', '@', '2026-09-11T00:35:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week1'),
  (2026, 1, 'Los Angeles Rams', 'San Francisco 49ers', 'vs', '2026-09-11T00:35:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week1'),
  (2026, 1, 'Chicago Bears', 'Carolina Panthers', '@', '2026-09-13T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week1'),
  (2026, 1, 'Carolina Panthers', 'Chicago Bears', 'vs', '2026-09-13T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week1'),
  (2026, 1, 'Tampa Bay Buccaneers', 'Cincinnati Bengals', '@', '2026-09-13T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week1'),
  (2026, 1, 'Cincinnati Bengals', 'Tampa Bay Buccaneers', 'vs', '2026-09-13T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week1'),
  (2026, 1, 'New Orleans Saints', 'Detroit Lions', '@', '2026-09-13T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week1'),
  (2026, 1, 'Detroit Lions', 'New Orleans Saints', 'vs', '2026-09-13T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week1'),
  (2026, 1, 'Buffalo Bills', 'Houston Texans', '@', '2026-09-13T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week1'),
  (2026, 1, 'Houston Texans', 'Buffalo Bills', 'vs', '2026-09-13T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week1'),
  (2026, 1, 'Baltimore Ravens', 'Indianapolis Colts', '@', '2026-09-13T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week1'),
  (2026, 1, 'Indianapolis Colts', 'Baltimore Ravens', 'vs', '2026-09-13T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week1'),
  (2026, 1, 'Cleveland Browns', 'Jacksonville Jaguars', '@', '2026-09-13T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week1'),
  (2026, 1, 'Jacksonville Jaguars', 'Cleveland Browns', 'vs', '2026-09-13T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week1'),
  (2026, 1, 'Atlanta Falcons', 'Pittsburgh Steelers', '@', '2026-09-13T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week1'),
  (2026, 1, 'Pittsburgh Steelers', 'Atlanta Falcons', 'vs', '2026-09-13T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week1'),
  (2026, 1, 'New York Jets', 'Tennessee Titans', '@', '2026-09-13T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week1'),
  (2026, 1, 'Tennessee Titans', 'New York Jets', 'vs', '2026-09-13T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week1'),
  (2026, 1, 'Arizona Cardinals', 'Los Angeles Chargers', '@', '2026-09-13T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week1'),
  (2026, 1, 'Los Angeles Chargers', 'Arizona Cardinals', 'vs', '2026-09-13T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week1'),
  (2026, 1, 'Miami Dolphins', 'Las Vegas Raiders', '@', '2026-09-13T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week1'),
  (2026, 1, 'Las Vegas Raiders', 'Miami Dolphins', 'vs', '2026-09-13T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week1'),
  (2026, 1, 'Green Bay Packers', 'Minnesota Vikings', '@', '2026-09-13T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week1'),
  (2026, 1, 'Minnesota Vikings', 'Green Bay Packers', 'vs', '2026-09-13T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week1'),
  (2026, 1, 'Washington Commanders', 'Philadelphia Eagles', '@', '2026-09-13T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week1'),
  (2026, 1, 'Philadelphia Eagles', 'Washington Commanders', 'vs', '2026-09-13T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week1'),
  (2026, 1, 'Dallas Cowboys', 'New York Giants', '@', '2026-09-14T00:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week1'),
  (2026, 1, 'New York Giants', 'Dallas Cowboys', 'vs', '2026-09-14T00:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week1'),
  (2026, 1, 'Denver Broncos', 'Kansas City Chiefs', '@', '2026-09-15T00:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week1'),
  (2026, 1, 'Kansas City Chiefs', 'Denver Broncos', 'vs', '2026-09-15T00:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week1'),
  (2026, 2, 'Detroit Lions', 'Buffalo Bills', '@', '2026-09-18T00:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week2'),
  (2026, 2, 'Buffalo Bills', 'Detroit Lions', 'vs', '2026-09-18T00:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week2'),
  (2026, 2, 'Carolina Panthers', 'Atlanta Falcons', '@', '2026-09-20T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week2'),
  (2026, 2, 'Atlanta Falcons', 'Carolina Panthers', 'vs', '2026-09-20T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week2'),
  (2026, 2, 'New Orleans Saints', 'Baltimore Ravens', '@', '2026-09-20T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week2'),
  (2026, 2, 'Baltimore Ravens', 'New Orleans Saints', 'vs', '2026-09-20T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week2'),
  (2026, 2, 'Minnesota Vikings', 'Chicago Bears', '@', '2026-09-20T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week2'),
  (2026, 2, 'Chicago Bears', 'Minnesota Vikings', 'vs', '2026-09-20T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week2'),
  (2026, 2, 'Cincinnati Bengals', 'Houston Texans', '@', '2026-09-20T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week2'),
  (2026, 2, 'Houston Texans', 'Cincinnati Bengals', 'vs', '2026-09-20T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week2'),
  (2026, 2, 'Pittsburgh Steelers', 'New England Patriots', '@', '2026-09-20T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week2'),
  (2026, 2, 'New England Patriots', 'Pittsburgh Steelers', 'vs', '2026-09-20T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week2'),
  (2026, 2, 'Green Bay Packers', 'New York Jets', '@', '2026-09-20T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week2'),
  (2026, 2, 'New York Jets', 'Green Bay Packers', 'vs', '2026-09-20T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week2'),
  (2026, 2, 'Cleveland Browns', 'Tampa Bay Buccaneers', '@', '2026-09-20T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week2'),
  (2026, 2, 'Tampa Bay Buccaneers', 'Cleveland Browns', 'vs', '2026-09-20T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week2'),
  (2026, 2, 'Philadelphia Eagles', 'Tennessee Titans', '@', '2026-09-20T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week2'),
  (2026, 2, 'Tennessee Titans', 'Philadelphia Eagles', 'vs', '2026-09-20T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week2'),
  (2026, 2, 'Jacksonville Jaguars', 'Denver Broncos', '@', '2026-09-20T20:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week2'),
  (2026, 2, 'Denver Broncos', 'Jacksonville Jaguars', 'vs', '2026-09-20T20:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week2'),
  (2026, 2, 'Las Vegas Raiders', 'Los Angeles Chargers', '@', '2026-09-20T20:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week2'),
  (2026, 2, 'Los Angeles Chargers', 'Las Vegas Raiders', 'vs', '2026-09-20T20:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week2'),
  (2026, 2, 'Seattle Seahawks', 'Arizona Cardinals', '@', '2026-09-20T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week2'),
  (2026, 2, 'Arizona Cardinals', 'Seattle Seahawks', 'vs', '2026-09-20T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week2'),
  (2026, 2, 'Washington Commanders', 'Dallas Cowboys', '@', '2026-09-20T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week2'),
  (2026, 2, 'Dallas Cowboys', 'Washington Commanders', 'vs', '2026-09-20T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week2'),
  (2026, 2, 'Miami Dolphins', 'San Francisco 49ers', '@', '2026-09-20T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week2'),
  (2026, 2, 'San Francisco 49ers', 'Miami Dolphins', 'vs', '2026-09-20T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week2'),
  (2026, 2, 'Indianapolis Colts', 'Kansas City Chiefs', '@', '2026-09-21T00:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week2'),
  (2026, 2, 'Kansas City Chiefs', 'Indianapolis Colts', 'vs', '2026-09-21T00:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week2'),
  (2026, 2, 'New York Giants', 'Los Angeles Rams', '@', '2026-09-22T00:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week2'),
  (2026, 2, 'Los Angeles Rams', 'New York Giants', 'vs', '2026-09-22T00:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week2'),
  (2026, 3, 'Atlanta Falcons', 'Green Bay Packers', '@', '2026-09-25T00:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week3'),
  (2026, 3, 'Green Bay Packers', 'Atlanta Falcons', 'vs', '2026-09-25T00:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week3'),
  (2026, 3, 'Los Angeles Chargers', 'Buffalo Bills', '@', '2026-09-27T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week3'),
  (2026, 3, 'Buffalo Bills', 'Los Angeles Chargers', 'vs', '2026-09-27T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week3'),
  (2026, 3, 'Carolina Panthers', 'Cleveland Browns', '@', '2026-09-27T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week3'),
  (2026, 3, 'Cleveland Browns', 'Carolina Panthers', 'vs', '2026-09-27T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week3'),
  (2026, 3, 'New York Jets', 'Detroit Lions', '@', '2026-09-27T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week3'),
  (2026, 3, 'Detroit Lions', 'New York Jets', 'vs', '2026-09-27T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week3'),
  (2026, 3, 'Houston Texans', 'Indianapolis Colts', '@', '2026-09-27T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week3'),
  (2026, 3, 'Indianapolis Colts', 'Houston Texans', 'vs', '2026-09-27T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week3'),
  (2026, 3, 'New England Patriots', 'Jacksonville Jaguars', '@', '2026-09-27T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week3'),
  (2026, 3, 'Jacksonville Jaguars', 'New England Patriots', 'vs', '2026-09-27T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week3'),
  (2026, 3, 'Kansas City Chiefs', 'Miami Dolphins', '@', '2026-09-27T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week3'),
  (2026, 3, 'Miami Dolphins', 'Kansas City Chiefs', 'vs', '2026-09-27T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week3'),
  (2026, 3, 'Tennessee Titans', 'New York Giants', '@', '2026-09-27T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week3'),
  (2026, 3, 'New York Giants', 'Tennessee Titans', 'vs', '2026-09-27T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week3'),
  (2026, 3, 'Cincinnati Bengals', 'Pittsburgh Steelers', '@', '2026-09-27T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week3'),
  (2026, 3, 'Pittsburgh Steelers', 'Cincinnati Bengals', 'vs', '2026-09-27T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week3'),
  (2026, 3, 'Seattle Seahawks', 'Washington Commanders', '@', '2026-09-27T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week3'),
  (2026, 3, 'Washington Commanders', 'Seattle Seahawks', 'vs', '2026-09-27T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week3'),
  (2026, 3, 'Arizona Cardinals', 'San Francisco 49ers', '@', '2026-09-27T20:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week3'),
  (2026, 3, 'San Francisco 49ers', 'Arizona Cardinals', 'vs', '2026-09-27T20:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week3'),
  (2026, 3, 'Minnesota Vikings', 'Tampa Bay Buccaneers', '@', '2026-09-27T20:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week3'),
  (2026, 3, 'Tampa Bay Buccaneers', 'Minnesota Vikings', 'vs', '2026-09-27T20:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week3'),
  (2026, 3, 'Baltimore Ravens', 'Dallas Cowboys', '@', '2026-09-27T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week3'),
  (2026, 3, 'Dallas Cowboys', 'Baltimore Ravens', 'vs', '2026-09-27T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week3'),
  (2026, 3, 'Las Vegas Raiders', 'New Orleans Saints', '@', '2026-09-27T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week3'),
  (2026, 3, 'New Orleans Saints', 'Las Vegas Raiders', 'vs', '2026-09-27T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week3'),
  (2026, 3, 'Los Angeles Rams', 'Denver Broncos', '@', '2026-09-28T00:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week3'),
  (2026, 3, 'Denver Broncos', 'Los Angeles Rams', 'vs', '2026-09-28T00:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week3'),
  (2026, 3, 'Philadelphia Eagles', 'Chicago Bears', '@', '2026-09-29T00:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week3'),
  (2026, 3, 'Chicago Bears', 'Philadelphia Eagles', 'vs', '2026-09-29T00:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week3'),
  (2026, 4, 'Pittsburgh Steelers', 'Cleveland Browns', '@', '2026-10-02T00:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week4'),
  (2026, 4, 'Cleveland Browns', 'Pittsburgh Steelers', 'vs', '2026-10-02T00:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week4'),
  (2026, 4, 'Indianapolis Colts', 'Washington Commanders', '@', '2026-10-04T13:30:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week4'),
  (2026, 4, 'Washington Commanders', 'Indianapolis Colts', 'vs', '2026-10-04T13:30:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week4'),
  (2026, 4, 'Tennessee Titans', 'Baltimore Ravens', '@', '2026-10-04T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week4'),
  (2026, 4, 'Baltimore Ravens', 'Tennessee Titans', 'vs', '2026-10-04T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week4'),
  (2026, 4, 'New England Patriots', 'Buffalo Bills', '@', '2026-10-04T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week4'),
  (2026, 4, 'Buffalo Bills', 'New England Patriots', 'vs', '2026-10-04T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week4'),
  (2026, 4, 'New York Jets', 'Chicago Bears', '@', '2026-10-04T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week4'),
  (2026, 4, 'Chicago Bears', 'New York Jets', 'vs', '2026-10-04T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week4'),
  (2026, 4, 'Jacksonville Jaguars', 'Cincinnati Bengals', '@', '2026-10-04T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week4'),
  (2026, 4, 'Cincinnati Bengals', 'Jacksonville Jaguars', 'vs', '2026-10-04T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week4'),
  (2026, 4, 'Dallas Cowboys', 'Houston Texans', '@', '2026-10-04T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week4'),
  (2026, 4, 'Houston Texans', 'Dallas Cowboys', 'vs', '2026-10-04T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week4'),
  (2026, 4, 'Arizona Cardinals', 'New York Giants', '@', '2026-10-04T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week4'),
  (2026, 4, 'New York Giants', 'Arizona Cardinals', 'vs', '2026-10-04T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week4'),
  (2026, 4, 'Los Angeles Rams', 'Philadelphia Eagles', '@', '2026-10-04T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week4'),
  (2026, 4, 'Philadelphia Eagles', 'Los Angeles Rams', 'vs', '2026-10-04T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week4'),
  (2026, 4, 'Green Bay Packers', 'Tampa Bay Buccaneers', '@', '2026-10-04T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week4'),
  (2026, 4, 'Tampa Bay Buccaneers', 'Green Bay Packers', 'vs', '2026-10-04T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week4'),
  (2026, 4, 'Miami Dolphins', 'Minnesota Vikings', '@', '2026-10-04T20:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week4'),
  (2026, 4, 'Minnesota Vikings', 'Miami Dolphins', 'vs', '2026-10-04T20:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week4'),
  (2026, 4, 'Kansas City Chiefs', 'Las Vegas Raiders', '@', '2026-10-04T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week4'),
  (2026, 4, 'Las Vegas Raiders', 'Kansas City Chiefs', 'vs', '2026-10-04T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week4'),
  (2026, 4, 'Los Angeles Chargers', 'Seattle Seahawks', '@', '2026-10-04T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week4'),
  (2026, 4, 'Seattle Seahawks', 'Los Angeles Chargers', 'vs', '2026-10-04T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week4'),
  (2026, 4, 'Denver Broncos', 'San Francisco 49ers', '@', '2026-10-04T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week4'),
  (2026, 4, 'San Francisco 49ers', 'Denver Broncos', 'vs', '2026-10-04T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week4'),
  (2026, 4, 'Detroit Lions', 'Carolina Panthers', '@', '2026-10-05T00:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week4'),
  (2026, 4, 'Carolina Panthers', 'Detroit Lions', 'vs', '2026-10-05T00:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week4'),
  (2026, 4, 'Atlanta Falcons', 'New Orleans Saints', '@', '2026-10-06T00:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week4'),
  (2026, 4, 'New Orleans Saints', 'Atlanta Falcons', 'vs', '2026-10-06T00:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week4'),
  (2026, 5, 'Tampa Bay Buccaneers', 'Dallas Cowboys', '@', '2026-10-09T00:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week5'),
  (2026, 5, 'Dallas Cowboys', 'Tampa Bay Buccaneers', 'vs', '2026-10-09T00:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week5'),
  (2026, 5, 'Philadelphia Eagles', 'Jacksonville Jaguars', '@', '2026-10-11T13:30:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week5'),
  (2026, 5, 'Jacksonville Jaguars', 'Philadelphia Eagles', 'vs', '2026-10-11T13:30:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week5'),
  (2026, 5, 'Cincinnati Bengals', 'Miami Dolphins', '@', '2026-10-11T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week5'),
  (2026, 5, 'Miami Dolphins', 'Cincinnati Bengals', 'vs', '2026-10-11T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week5'),
  (2026, 5, 'Las Vegas Raiders', 'New England Patriots', '@', '2026-10-11T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week5'),
  (2026, 5, 'New England Patriots', 'Las Vegas Raiders', 'vs', '2026-10-11T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week5'),
  (2026, 5, 'Minnesota Vikings', 'New Orleans Saints', '@', '2026-10-11T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week5'),
  (2026, 5, 'New Orleans Saints', 'Minnesota Vikings', 'vs', '2026-10-11T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week5'),
  (2026, 5, 'Cleveland Browns', 'New York Jets', '@', '2026-10-11T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week5'),
  (2026, 5, 'New York Jets', 'Cleveland Browns', 'vs', '2026-10-11T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week5'),
  (2026, 5, 'Indianapolis Colts', 'Pittsburgh Steelers', '@', '2026-10-11T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week5'),
  (2026, 5, 'Pittsburgh Steelers', 'Indianapolis Colts', 'vs', '2026-10-11T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week5'),
  (2026, 5, 'Houston Texans', 'Tennessee Titans', '@', '2026-10-11T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week5'),
  (2026, 5, 'Tennessee Titans', 'Houston Texans', 'vs', '2026-10-11T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week5'),
  (2026, 5, 'New York Giants', 'Washington Commanders', '@', '2026-10-11T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week5'),
  (2026, 5, 'Washington Commanders', 'New York Giants', 'vs', '2026-10-11T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week5'),
  (2026, 5, 'Denver Broncos', 'Los Angeles Chargers', '@', '2026-10-11T20:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week5'),
  (2026, 5, 'Los Angeles Chargers', 'Denver Broncos', 'vs', '2026-10-11T20:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week5'),
  (2026, 5, 'Detroit Lions', 'Arizona Cardinals', '@', '2026-10-11T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week5'),
  (2026, 5, 'Arizona Cardinals', 'Detroit Lions', 'vs', '2026-10-11T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week5'),
  (2026, 5, 'Chicago Bears', 'Green Bay Packers', '@', '2026-10-11T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week5'),
  (2026, 5, 'Green Bay Packers', 'Chicago Bears', 'vs', '2026-10-11T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week5'),
  (2026, 5, 'San Francisco 49ers', 'Seattle Seahawks', '@', '2026-10-11T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week5'),
  (2026, 5, 'Seattle Seahawks', 'San Francisco 49ers', 'vs', '2026-10-11T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week5'),
  (2026, 5, 'Baltimore Ravens', 'Atlanta Falcons', '@', '2026-10-12T00:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week5'),
  (2026, 5, 'Atlanta Falcons', 'Baltimore Ravens', 'vs', '2026-10-12T00:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week5'),
  (2026, 5, 'Buffalo Bills', 'Los Angeles Rams', '@', '2026-10-13T00:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week5'),
  (2026, 5, 'Los Angeles Rams', 'Buffalo Bills', 'vs', '2026-10-13T00:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week5'),
  (2026, 6, 'Seattle Seahawks', 'Denver Broncos', '@', '2026-10-16T00:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week6'),
  (2026, 6, 'Denver Broncos', 'Seattle Seahawks', 'vs', '2026-10-16T00:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week6'),
  (2026, 6, 'Houston Texans', 'Jacksonville Jaguars', '@', '2026-10-18T13:30:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week6'),
  (2026, 6, 'Jacksonville Jaguars', 'Houston Texans', 'vs', '2026-10-18T13:30:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week6'),
  (2026, 6, 'Chicago Bears', 'Atlanta Falcons', '@', '2026-10-18T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week6'),
  (2026, 6, 'Atlanta Falcons', 'Chicago Bears', 'vs', '2026-10-18T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week6'),
  (2026, 6, 'Baltimore Ravens', 'Cleveland Browns', '@', '2026-10-18T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week6'),
  (2026, 6, 'Cleveland Browns', 'Baltimore Ravens', 'vs', '2026-10-18T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week6'),
  (2026, 6, 'Tennessee Titans', 'Indianapolis Colts', '@', '2026-10-18T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week6'),
  (2026, 6, 'Indianapolis Colts', 'Tennessee Titans', 'vs', '2026-10-18T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week6'),
  (2026, 6, 'New York Jets', 'New England Patriots', '@', '2026-10-18T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week6'),
  (2026, 6, 'New England Patriots', 'New York Jets', 'vs', '2026-10-18T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week6'),
  (2026, 6, 'New Orleans Saints', 'New York Giants', '@', '2026-10-18T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week6'),
  (2026, 6, 'New York Giants', 'New Orleans Saints', 'vs', '2026-10-18T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week6'),
  (2026, 6, 'Carolina Panthers', 'Philadelphia Eagles', '@', '2026-10-18T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week6'),
  (2026, 6, 'Philadelphia Eagles', 'Carolina Panthers', 'vs', '2026-10-18T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week6'),
  (2026, 6, 'Pittsburgh Steelers', 'Tampa Bay Buccaneers', '@', '2026-10-18T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week6'),
  (2026, 6, 'Tampa Bay Buccaneers', 'Pittsburgh Steelers', 'vs', '2026-10-18T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week6'),
  (2026, 6, 'Arizona Cardinals', 'Los Angeles Rams', '@', '2026-10-18T20:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week6'),
  (2026, 6, 'Los Angeles Rams', 'Arizona Cardinals', 'vs', '2026-10-18T20:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week6'),
  (2026, 6, 'Los Angeles Chargers', 'Kansas City Chiefs', '@', '2026-10-18T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week6'),
  (2026, 6, 'Kansas City Chiefs', 'Los Angeles Chargers', 'vs', '2026-10-18T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week6'),
  (2026, 6, 'Buffalo Bills', 'Las Vegas Raiders', '@', '2026-10-18T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week6'),
  (2026, 6, 'Las Vegas Raiders', 'Buffalo Bills', 'vs', '2026-10-18T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week6'),
  (2026, 6, 'Dallas Cowboys', 'Green Bay Packers', '@', '2026-10-19T00:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week6'),
  (2026, 6, 'Green Bay Packers', 'Dallas Cowboys', 'vs', '2026-10-19T00:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week6'),
  (2026, 6, 'Washington Commanders', 'San Francisco 49ers', '@', '2026-10-20T00:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week6'),
  (2026, 6, 'San Francisco 49ers', 'Washington Commanders', 'vs', '2026-10-20T00:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week6'),
  (2026, 7, 'New England Patriots', 'Chicago Bears', '@', '2026-10-23T00:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week7'),
  (2026, 7, 'Chicago Bears', 'New England Patriots', 'vs', '2026-10-23T00:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week7'),
  (2026, 7, 'Pittsburgh Steelers', 'New Orleans Saints', '@', '2026-10-25T13:30:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week7'),
  (2026, 7, 'New Orleans Saints', 'Pittsburgh Steelers', 'vs', '2026-10-25T13:30:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week7'),
  (2026, 7, 'San Francisco 49ers', 'Atlanta Falcons', '@', '2026-10-25T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week7'),
  (2026, 7, 'Atlanta Falcons', 'San Francisco 49ers', 'vs', '2026-10-25T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week7'),
  (2026, 7, 'Cincinnati Bengals', 'Baltimore Ravens', '@', '2026-10-25T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week7'),
  (2026, 7, 'Baltimore Ravens', 'Cincinnati Bengals', 'vs', '2026-10-25T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week7'),
  (2026, 7, 'Tampa Bay Buccaneers', 'Carolina Panthers', '@', '2026-10-25T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week7'),
  (2026, 7, 'Carolina Panthers', 'Tampa Bay Buccaneers', 'vs', '2026-10-25T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week7'),
  (2026, 7, 'New York Giants', 'Houston Texans', '@', '2026-10-25T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week7'),
  (2026, 7, 'Houston Texans', 'New York Giants', 'vs', '2026-10-25T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week7'),
  (2026, 7, 'Indianapolis Colts', 'Minnesota Vikings', '@', '2026-10-25T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week7'),
  (2026, 7, 'Minnesota Vikings', 'Indianapolis Colts', 'vs', '2026-10-25T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week7'),
  (2026, 7, 'Miami Dolphins', 'New York Jets', '@', '2026-10-25T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week7'),
  (2026, 7, 'New York Jets', 'Miami Dolphins', 'vs', '2026-10-25T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week7'),
  (2026, 7, 'Cleveland Browns', 'Tennessee Titans', '@', '2026-10-25T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week7'),
  (2026, 7, 'Tennessee Titans', 'Cleveland Browns', 'vs', '2026-10-25T17:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week7'),
  (2026, 7, 'Denver Broncos', 'Arizona Cardinals', '@', '2026-10-25T20:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week7'),
  (2026, 7, 'Arizona Cardinals', 'Denver Broncos', 'vs', '2026-10-25T20:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week7'),
  (2026, 7, 'Green Bay Packers', 'Detroit Lions', '@', '2026-10-25T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week7'),
  (2026, 7, 'Detroit Lions', 'Green Bay Packers', 'vs', '2026-10-25T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week7'),
  (2026, 7, 'Los Angeles Rams', 'Las Vegas Raiders', '@', '2026-10-25T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week7'),
  (2026, 7, 'Las Vegas Raiders', 'Los Angeles Rams', 'vs', '2026-10-25T20:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week7'),
  (2026, 7, 'Kansas City Chiefs', 'Seattle Seahawks', '@', '2026-10-26T00:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week7'),
  (2026, 7, 'Seattle Seahawks', 'Kansas City Chiefs', 'vs', '2026-10-26T00:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week7'),
  (2026, 7, 'Dallas Cowboys', 'Philadelphia Eagles', '@', '2026-10-27T00:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week7'),
  (2026, 7, 'Philadelphia Eagles', 'Dallas Cowboys', 'vs', '2026-10-27T00:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week7'),
  (2026, 8, 'Carolina Panthers', 'Green Bay Packers', '@', '2026-10-30T00:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week8'),
  (2026, 8, 'Green Bay Packers', 'Carolina Panthers', 'vs', '2026-10-30T00:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week8'),
  (2026, 8, 'Baltimore Ravens', 'Buffalo Bills', '@', '2026-11-01T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week8'),
  (2026, 8, 'Buffalo Bills', 'Baltimore Ravens', 'vs', '2026-11-01T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week8'),
  (2026, 8, 'Tennessee Titans', 'Cincinnati Bengals', '@', '2026-11-01T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week8'),
  (2026, 8, 'Cincinnati Bengals', 'Tennessee Titans', 'vs', '2026-11-01T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week8'),
  (2026, 8, 'Arizona Cardinals', 'Dallas Cowboys', '@', '2026-11-01T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week8'),
  (2026, 8, 'Dallas Cowboys', 'Arizona Cardinals', 'vs', '2026-11-01T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week8'),
  (2026, 8, 'Minnesota Vikings', 'Detroit Lions', '@', '2026-11-01T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week8'),
  (2026, 8, 'Detroit Lions', 'Minnesota Vikings', 'vs', '2026-11-01T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week8'),
  (2026, 8, 'Indianapolis Colts', 'Jacksonville Jaguars', '@', '2026-11-01T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week8'),
  (2026, 8, 'Jacksonville Jaguars', 'Indianapolis Colts', 'vs', '2026-11-01T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week8'),
  (2026, 8, 'Las Vegas Raiders', 'New York Jets', '@', '2026-11-01T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week8'),
  (2026, 8, 'New York Jets', 'Las Vegas Raiders', 'vs', '2026-11-01T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week8'),
  (2026, 8, 'Cleveland Browns', 'Pittsburgh Steelers', '@', '2026-11-01T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week8'),
  (2026, 8, 'Pittsburgh Steelers', 'Cleveland Browns', 'vs', '2026-11-01T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week8'),
  (2026, 8, 'Atlanta Falcons', 'Tampa Bay Buccaneers', '@', '2026-11-01T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week8'),
  (2026, 8, 'Tampa Bay Buccaneers', 'Atlanta Falcons', 'vs', '2026-11-01T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week8'),
  (2026, 8, 'Los Angeles Chargers', 'Los Angeles Rams', '@', '2026-11-01T21:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week8'),
  (2026, 8, 'Los Angeles Rams', 'Los Angeles Chargers', 'vs', '2026-11-01T21:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week8'),
  (2026, 8, 'Kansas City Chiefs', 'Denver Broncos', '@', '2026-11-01T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week8'),
  (2026, 8, 'Denver Broncos', 'Kansas City Chiefs', 'vs', '2026-11-01T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week8'),
  (2026, 8, 'New England Patriots', 'Miami Dolphins', '@', '2026-11-01T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week8'),
  (2026, 8, 'Miami Dolphins', 'New England Patriots', 'vs', '2026-11-01T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week8'),
  (2026, 8, 'Philadelphia Eagles', 'Washington Commanders', '@', '2026-11-02T01:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week8'),
  (2026, 8, 'Washington Commanders', 'Philadelphia Eagles', 'vs', '2026-11-02T01:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week8'),
  (2026, 8, 'Chicago Bears', 'Seattle Seahawks', '@', '2026-11-03T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week8'),
  (2026, 8, 'Seattle Seahawks', 'Chicago Bears', 'vs', '2026-11-03T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week8'),
  (2026, 9, 'Jacksonville Jaguars', 'Baltimore Ravens', '@', '2026-11-06T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week9'),
  (2026, 9, 'Baltimore Ravens', 'Jacksonville Jaguars', 'vs', '2026-11-06T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week9'),
  (2026, 9, 'Cincinnati Bengals', 'Atlanta Falcons', '@', '2026-11-08T14:30:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week9'),
  (2026, 9, 'Atlanta Falcons', 'Cincinnati Bengals', 'vs', '2026-11-08T14:30:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week9'),
  (2026, 9, 'Denver Broncos', 'Carolina Panthers', '@', '2026-11-08T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week9'),
  (2026, 9, 'Carolina Panthers', 'Denver Broncos', 'vs', '2026-11-08T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week9'),
  (2026, 9, 'Dallas Cowboys', 'Indianapolis Colts', '@', '2026-11-08T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week9'),
  (2026, 9, 'Indianapolis Colts', 'Dallas Cowboys', 'vs', '2026-11-08T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week9'),
  (2026, 9, 'New York Jets', 'Kansas City Chiefs', '@', '2026-11-08T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week9'),
  (2026, 9, 'Kansas City Chiefs', 'New York Jets', 'vs', '2026-11-08T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week9'),
  (2026, 9, 'Detroit Lions', 'Miami Dolphins', '@', '2026-11-08T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week9'),
  (2026, 9, 'Miami Dolphins', 'Detroit Lions', 'vs', '2026-11-08T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week9'),
  (2026, 9, 'Cleveland Browns', 'New Orleans Saints', '@', '2026-11-08T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week9'),
  (2026, 9, 'New Orleans Saints', 'Cleveland Browns', 'vs', '2026-11-08T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week9'),
  (2026, 9, 'New York Giants', 'Philadelphia Eagles', '@', '2026-11-08T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week9'),
  (2026, 9, 'Philadelphia Eagles', 'New York Giants', 'vs', '2026-11-08T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week9'),
  (2026, 9, 'Los Angeles Rams', 'Washington Commanders', '@', '2026-11-08T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week9'),
  (2026, 9, 'Washington Commanders', 'Los Angeles Rams', 'vs', '2026-11-08T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week9'),
  (2026, 9, 'Houston Texans', 'Los Angeles Chargers', '@', '2026-11-08T21:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week9'),
  (2026, 9, 'Los Angeles Chargers', 'Houston Texans', 'vs', '2026-11-08T21:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week9'),
  (2026, 9, 'Las Vegas Raiders', 'San Francisco 49ers', '@', '2026-11-08T21:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week9'),
  (2026, 9, 'San Francisco 49ers', 'Las Vegas Raiders', 'vs', '2026-11-08T21:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week9'),
  (2026, 9, 'Green Bay Packers', 'New England Patriots', '@', '2026-11-08T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week9'),
  (2026, 9, 'New England Patriots', 'Green Bay Packers', 'vs', '2026-11-08T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week9'),
  (2026, 9, 'Arizona Cardinals', 'Seattle Seahawks', '@', '2026-11-08T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week9'),
  (2026, 9, 'Seattle Seahawks', 'Arizona Cardinals', 'vs', '2026-11-08T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week9'),
  (2026, 9, 'Tampa Bay Buccaneers', 'Chicago Bears', '@', '2026-11-09T01:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week9'),
  (2026, 9, 'Chicago Bears', 'Tampa Bay Buccaneers', 'vs', '2026-11-09T01:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week9'),
  (2026, 9, 'Buffalo Bills', 'Minnesota Vikings', '@', '2026-11-10T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week9'),
  (2026, 9, 'Minnesota Vikings', 'Buffalo Bills', 'vs', '2026-11-10T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week9'),
  (2026, 10, 'Washington Commanders', 'New York Giants', '@', '2026-11-13T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week10'),
  (2026, 10, 'New York Giants', 'Washington Commanders', 'vs', '2026-11-13T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week10'),
  (2026, 10, 'New England Patriots', 'Detroit Lions', '@', '2026-11-15T14:30:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week10'),
  (2026, 10, 'Detroit Lions', 'New England Patriots', 'vs', '2026-11-15T14:30:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week10'),
  (2026, 10, 'Kansas City Chiefs', 'Atlanta Falcons', '@', '2026-11-15T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week10'),
  (2026, 10, 'Atlanta Falcons', 'Kansas City Chiefs', 'vs', '2026-11-15T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week10'),
  (2026, 10, 'Houston Texans', 'Cleveland Browns', '@', '2026-11-15T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week10'),
  (2026, 10, 'Cleveland Browns', 'Houston Texans', 'vs', '2026-11-15T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week10'),
  (2026, 10, 'Minnesota Vikings', 'Green Bay Packers', '@', '2026-11-15T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week10'),
  (2026, 10, 'Green Bay Packers', 'Minnesota Vikings', 'vs', '2026-11-15T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week10'),
  (2026, 10, 'Miami Dolphins', 'Indianapolis Colts', '@', '2026-11-15T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week10'),
  (2026, 10, 'Indianapolis Colts', 'Miami Dolphins', 'vs', '2026-11-15T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week10'),
  (2026, 10, 'Carolina Panthers', 'New Orleans Saints', '@', '2026-11-15T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week10'),
  (2026, 10, 'New Orleans Saints', 'Carolina Panthers', 'vs', '2026-11-15T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week10'),
  (2026, 10, 'Buffalo Bills', 'New York Jets', '@', '2026-11-15T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week10'),
  (2026, 10, 'New York Jets', 'Buffalo Bills', 'vs', '2026-11-15T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week10'),
  (2026, 10, 'Jacksonville Jaguars', 'Tennessee Titans', '@', '2026-11-15T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week10'),
  (2026, 10, 'Tennessee Titans', 'Jacksonville Jaguars', 'vs', '2026-11-15T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week10'),
  (2026, 10, 'Los Angeles Rams', 'Arizona Cardinals', '@', '2026-11-15T21:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week10'),
  (2026, 10, 'Arizona Cardinals', 'Los Angeles Rams', 'vs', '2026-11-15T21:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week10'),
  (2026, 10, 'Seattle Seahawks', 'Las Vegas Raiders', '@', '2026-11-15T21:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week10'),
  (2026, 10, 'Las Vegas Raiders', 'Seattle Seahawks', 'vs', '2026-11-15T21:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week10'),
  (2026, 10, 'San Francisco 49ers', 'Dallas Cowboys', '@', '2026-11-15T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week10'),
  (2026, 10, 'Dallas Cowboys', 'San Francisco 49ers', 'vs', '2026-11-15T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week10'),
  (2026, 10, 'Pittsburgh Steelers', 'Cincinnati Bengals', '@', '2026-11-16T01:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week10'),
  (2026, 10, 'Cincinnati Bengals', 'Pittsburgh Steelers', 'vs', '2026-11-16T01:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week10'),
  (2026, 10, 'Los Angeles Chargers', 'Baltimore Ravens', '@', '2026-11-17T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week10'),
  (2026, 10, 'Baltimore Ravens', 'Los Angeles Chargers', 'vs', '2026-11-17T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week10'),
  (2026, 11, 'Indianapolis Colts', 'Houston Texans', '@', '2026-11-20T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week11'),
  (2026, 11, 'Houston Texans', 'Indianapolis Colts', 'vs', '2026-11-20T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week11'),
  (2026, 11, 'Miami Dolphins', 'Buffalo Bills', '@', '2026-11-22T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week11'),
  (2026, 11, 'Buffalo Bills', 'Miami Dolphins', 'vs', '2026-11-22T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week11'),
  (2026, 11, 'Baltimore Ravens', 'Carolina Panthers', '@', '2026-11-22T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week11'),
  (2026, 11, 'Carolina Panthers', 'Baltimore Ravens', 'vs', '2026-11-22T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week11'),
  (2026, 11, 'New Orleans Saints', 'Chicago Bears', '@', '2026-11-22T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week11'),
  (2026, 11, 'Chicago Bears', 'New Orleans Saints', 'vs', '2026-11-22T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week11'),
  (2026, 11, 'Tennessee Titans', 'Dallas Cowboys', '@', '2026-11-22T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week11'),
  (2026, 11, 'Dallas Cowboys', 'Tennessee Titans', 'vs', '2026-11-22T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week11'),
  (2026, 11, 'Tampa Bay Buccaneers', 'Detroit Lions', '@', '2026-11-22T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week11'),
  (2026, 11, 'Detroit Lions', 'Tampa Bay Buccaneers', 'vs', '2026-11-22T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week11'),
  (2026, 11, 'Arizona Cardinals', 'Kansas City Chiefs', '@', '2026-11-22T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week11'),
  (2026, 11, 'Kansas City Chiefs', 'Arizona Cardinals', 'vs', '2026-11-22T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week11'),
  (2026, 11, 'Jacksonville Jaguars', 'New York Giants', '@', '2026-11-22T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week11'),
  (2026, 11, 'New York Giants', 'Jacksonville Jaguars', 'vs', '2026-11-22T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week11'),
  (2026, 11, 'New York Jets', 'Los Angeles Chargers', '@', '2026-11-22T21:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week11'),
  (2026, 11, 'Los Angeles Chargers', 'New York Jets', 'vs', '2026-11-22T21:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week11'),
  (2026, 11, 'Las Vegas Raiders', 'Denver Broncos', '@', '2026-11-22T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week11'),
  (2026, 11, 'Denver Broncos', 'Las Vegas Raiders', 'vs', '2026-11-22T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week11'),
  (2026, 11, 'Pittsburgh Steelers', 'Philadelphia Eagles', '@', '2026-11-22T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week11'),
  (2026, 11, 'Philadelphia Eagles', 'Pittsburgh Steelers', 'vs', '2026-11-22T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week11'),
  (2026, 11, 'Minnesota Vikings', 'San Francisco 49ers', '@', '2026-11-23T01:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week11'),
  (2026, 11, 'San Francisco 49ers', 'Minnesota Vikings', 'vs', '2026-11-23T01:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week11'),
  (2026, 11, 'Cincinnati Bengals', 'Washington Commanders', '@', '2026-11-24T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week11'),
  (2026, 11, 'Washington Commanders', 'Cincinnati Bengals', 'vs', '2026-11-24T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week11'),
  (2026, 12, 'Green Bay Packers', 'Los Angeles Rams', '@', '2026-11-26T01:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week12'),
  (2026, 12, 'Los Angeles Rams', 'Green Bay Packers', 'vs', '2026-11-26T01:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week12'),
  (2026, 12, 'Chicago Bears', 'Detroit Lions', '@', '2026-11-26T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week12'),
  (2026, 12, 'Detroit Lions', 'Chicago Bears', 'vs', '2026-11-26T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week12'),
  (2026, 12, 'Philadelphia Eagles', 'Dallas Cowboys', '@', '2026-11-26T21:30:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week12'),
  (2026, 12, 'Dallas Cowboys', 'Philadelphia Eagles', 'vs', '2026-11-26T21:30:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week12'),
  (2026, 12, 'Kansas City Chiefs', 'Buffalo Bills', '@', '2026-11-27T01:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week12'),
  (2026, 12, 'Buffalo Bills', 'Kansas City Chiefs', 'vs', '2026-11-27T01:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week12'),
  (2026, 12, 'Denver Broncos', 'Pittsburgh Steelers', '@', '2026-11-27T20:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week12'),
  (2026, 12, 'Pittsburgh Steelers', 'Denver Broncos', 'vs', '2026-11-27T20:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week12'),
  (2026, 12, 'New Orleans Saints', 'Cincinnati Bengals', '@', '2026-11-29T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week12'),
  (2026, 12, 'Cincinnati Bengals', 'New Orleans Saints', 'vs', '2026-11-29T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week12'),
  (2026, 12, 'Las Vegas Raiders', 'Cleveland Browns', '@', '2026-11-29T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week12'),
  (2026, 12, 'Cleveland Browns', 'Las Vegas Raiders', 'vs', '2026-11-29T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week12'),
  (2026, 12, 'Baltimore Ravens', 'Houston Texans', '@', '2026-11-29T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week12'),
  (2026, 12, 'Houston Texans', 'Baltimore Ravens', 'vs', '2026-11-29T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week12'),
  (2026, 12, 'New York Giants', 'Indianapolis Colts', '@', '2026-11-29T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week12'),
  (2026, 12, 'Indianapolis Colts', 'New York Giants', 'vs', '2026-11-29T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week12'),
  (2026, 12, 'New York Jets', 'Miami Dolphins', '@', '2026-11-29T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week12'),
  (2026, 12, 'Miami Dolphins', 'New York Jets', 'vs', '2026-11-29T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week12'),
  (2026, 12, 'Atlanta Falcons', 'Minnesota Vikings', '@', '2026-11-29T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week12'),
  (2026, 12, 'Minnesota Vikings', 'Atlanta Falcons', 'vs', '2026-11-29T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week12'),
  (2026, 12, 'Tennessee Titans', 'Jacksonville Jaguars', '@', '2026-11-29T21:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week12'),
  (2026, 12, 'Jacksonville Jaguars', 'Tennessee Titans', 'vs', '2026-11-29T21:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week12'),
  (2026, 12, 'Washington Commanders', 'Arizona Cardinals', '@', '2026-11-29T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week12'),
  (2026, 12, 'Arizona Cardinals', 'Washington Commanders', 'vs', '2026-11-29T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week12'),
  (2026, 12, 'Seattle Seahawks', 'San Francisco 49ers', '@', '2026-11-29T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week12'),
  (2026, 12, 'San Francisco 49ers', 'Seattle Seahawks', 'vs', '2026-11-29T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week12'),
  (2026, 12, 'New England Patriots', 'Los Angeles Chargers', '@', '2026-11-30T01:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week12'),
  (2026, 12, 'Los Angeles Chargers', 'New England Patriots', 'vs', '2026-11-30T01:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week12'),
  (2026, 12, 'Carolina Panthers', 'Tampa Bay Buccaneers', '@', '2026-12-01T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week12'),
  (2026, 12, 'Tampa Bay Buccaneers', 'Carolina Panthers', 'vs', '2026-12-01T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week12'),
  (2026, 13, 'Kansas City Chiefs', 'Los Angeles Rams', '@', '2026-12-04T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week13'),
  (2026, 13, 'Los Angeles Rams', 'Kansas City Chiefs', 'vs', '2026-12-04T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week13'),
  (2026, 13, 'Detroit Lions', 'Atlanta Falcons', '@', '2026-12-06T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week13'),
  (2026, 13, 'Atlanta Falcons', 'Detroit Lions', 'vs', '2026-12-06T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week13'),
  (2026, 13, 'Jacksonville Jaguars', 'Chicago Bears', '@', '2026-12-06T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week13'),
  (2026, 13, 'Chicago Bears', 'Jacksonville Jaguars', 'vs', '2026-12-06T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week13'),
  (2026, 13, 'Cincinnati Bengals', 'Cleveland Browns', '@', '2026-12-06T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week13'),
  (2026, 13, 'Cleveland Browns', 'Cincinnati Bengals', 'vs', '2026-12-06T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week13'),
  (2026, 13, 'Green Bay Packers', 'New Orleans Saints', '@', '2026-12-06T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week13'),
  (2026, 13, 'New Orleans Saints', 'Green Bay Packers', 'vs', '2026-12-06T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week13'),
  (2026, 13, 'San Francisco 49ers', 'New York Giants', '@', '2026-12-06T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week13'),
  (2026, 13, 'New York Giants', 'San Francisco 49ers', 'vs', '2026-12-06T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week13'),
  (2026, 13, 'Los Angeles Chargers', 'Tampa Bay Buccaneers', '@', '2026-12-06T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week13'),
  (2026, 13, 'Tampa Bay Buccaneers', 'Los Angeles Chargers', 'vs', '2026-12-06T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week13'),
  (2026, 13, 'Washington Commanders', 'Tennessee Titans', '@', '2026-12-06T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week13'),
  (2026, 13, 'Tennessee Titans', 'Washington Commanders', 'vs', '2026-12-06T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week13'),
  (2026, 13, 'Philadelphia Eagles', 'Arizona Cardinals', '@', '2026-12-06T21:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week13'),
  (2026, 13, 'Arizona Cardinals', 'Philadelphia Eagles', 'vs', '2026-12-06T21:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week13'),
  (2026, 13, 'Miami Dolphins', 'Denver Broncos', '@', '2026-12-06T21:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week13'),
  (2026, 13, 'Denver Broncos', 'Miami Dolphins', 'vs', '2026-12-06T21:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week13'),
  (2026, 13, 'Carolina Panthers', 'Minnesota Vikings', '@', '2026-12-06T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week13'),
  (2026, 13, 'Minnesota Vikings', 'Carolina Panthers', 'vs', '2026-12-06T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week13'),
  (2026, 13, 'Buffalo Bills', 'New England Patriots', '@', '2026-12-06T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week13'),
  (2026, 13, 'New England Patriots', 'Buffalo Bills', 'vs', '2026-12-06T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week13'),
  (2026, 13, 'Houston Texans', 'Pittsburgh Steelers', '@', '2026-12-07T01:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week13'),
  (2026, 13, 'Pittsburgh Steelers', 'Houston Texans', 'vs', '2026-12-07T01:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week13'),
  (2026, 13, 'Dallas Cowboys', 'Seattle Seahawks', '@', '2026-12-08T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week13'),
  (2026, 13, 'Seattle Seahawks', 'Dallas Cowboys', 'vs', '2026-12-08T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week13'),
  (2026, 14, 'Minnesota Vikings', 'New England Patriots', '@', '2026-12-11T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week14'),
  (2026, 14, 'New England Patriots', 'Minnesota Vikings', 'vs', '2026-12-11T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week14'),
  (2026, 14, 'Tampa Bay Buccaneers', 'Baltimore Ravens', '@', '2026-12-13T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week14'),
  (2026, 14, 'Baltimore Ravens', 'Tampa Bay Buccaneers', 'vs', '2026-12-13T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week14'),
  (2026, 14, 'New Orleans Saints', 'Carolina Panthers', '@', '2026-12-13T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week14'),
  (2026, 14, 'Carolina Panthers', 'New Orleans Saints', 'vs', '2026-12-13T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week14'),
  (2026, 14, 'Atlanta Falcons', 'Cleveland Browns', '@', '2026-12-13T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week14'),
  (2026, 14, 'Cleveland Browns', 'Atlanta Falcons', 'vs', '2026-12-13T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week14'),
  (2026, 14, 'Tennessee Titans', 'Detroit Lions', '@', '2026-12-13T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week14'),
  (2026, 14, 'Detroit Lions', 'Tennessee Titans', 'vs', '2026-12-13T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week14'),
  (2026, 14, 'Chicago Bears', 'Miami Dolphins', '@', '2026-12-13T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week14'),
  (2026, 14, 'Miami Dolphins', 'Chicago Bears', 'vs', '2026-12-13T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week14'),
  (2026, 14, 'Denver Broncos', 'New York Jets', '@', '2026-12-13T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week14'),
  (2026, 14, 'New York Jets', 'Denver Broncos', 'vs', '2026-12-13T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week14'),
  (2026, 14, 'Indianapolis Colts', 'Philadelphia Eagles', '@', '2026-12-13T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week14'),
  (2026, 14, 'Philadelphia Eagles', 'Indianapolis Colts', 'vs', '2026-12-13T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week14'),
  (2026, 14, 'Houston Texans', 'Washington Commanders', '@', '2026-12-13T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week14'),
  (2026, 14, 'Washington Commanders', 'Houston Texans', 'vs', '2026-12-13T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week14'),
  (2026, 14, 'Los Angeles Chargers', 'Las Vegas Raiders', '@', '2026-12-13T21:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week14'),
  (2026, 14, 'Las Vegas Raiders', 'Los Angeles Chargers', 'vs', '2026-12-13T21:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week14'),
  (2026, 14, 'Kansas City Chiefs', 'Cincinnati Bengals', '@', '2026-12-13T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week14'),
  (2026, 14, 'Cincinnati Bengals', 'Kansas City Chiefs', 'vs', '2026-12-13T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week14'),
  (2026, 14, 'New York Giants', 'Seattle Seahawks', '@', '2026-12-13T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week14'),
  (2026, 14, 'Seattle Seahawks', 'New York Giants', 'vs', '2026-12-13T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week14'),
  (2026, 14, 'Los Angeles Rams', 'San Francisco 49ers', '@', '2026-12-13T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week14'),
  (2026, 14, 'San Francisco 49ers', 'Los Angeles Rams', 'vs', '2026-12-13T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week14'),
  (2026, 14, 'Buffalo Bills', 'Green Bay Packers', '@', '2026-12-14T01:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week14'),
  (2026, 14, 'Green Bay Packers', 'Buffalo Bills', 'vs', '2026-12-14T01:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week14'),
  (2026, 14, 'Pittsburgh Steelers', 'Jacksonville Jaguars', '@', '2026-12-15T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week14'),
  (2026, 14, 'Jacksonville Jaguars', 'Pittsburgh Steelers', 'vs', '2026-12-15T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week14'),
  (2026, 15, 'San Francisco 49ers', 'Los Angeles Chargers', '@', '2026-12-18T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week15'),
  (2026, 15, 'Los Angeles Chargers', 'San Francisco 49ers', 'vs', '2026-12-18T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week15'),
  (2026, 15, 'Seattle Seahawks', 'Philadelphia Eagles', '@', '2026-12-19T22:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week15'),
  (2026, 15, 'Philadelphia Eagles', 'Seattle Seahawks', 'vs', '2026-12-19T22:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week15'),
  (2026, 15, 'Chicago Bears', 'Buffalo Bills', '@', '2026-12-20T01:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week15'),
  (2026, 15, 'Buffalo Bills', 'Chicago Bears', 'vs', '2026-12-20T01:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week15'),
  (2026, 15, 'Cincinnati Bengals', 'Carolina Panthers', '@', '2026-12-20T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week15'),
  (2026, 15, 'Carolina Panthers', 'Cincinnati Bengals', 'vs', '2026-12-20T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week15'),
  (2026, 15, 'Miami Dolphins', 'Green Bay Packers', '@', '2026-12-20T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week15'),
  (2026, 15, 'Green Bay Packers', 'Miami Dolphins', 'vs', '2026-12-20T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week15'),
  (2026, 15, 'Jacksonville Jaguars', 'Houston Texans', '@', '2026-12-20T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week15'),
  (2026, 15, 'Houston Texans', 'Jacksonville Jaguars', 'vs', '2026-12-20T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week15'),
  (2026, 15, 'Cleveland Browns', 'New York Giants', '@', '2026-12-20T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week15'),
  (2026, 15, 'New York Giants', 'Cleveland Browns', 'vs', '2026-12-20T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week15'),
  (2026, 15, 'Baltimore Ravens', 'Pittsburgh Steelers', '@', '2026-12-20T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week15'),
  (2026, 15, 'Pittsburgh Steelers', 'Baltimore Ravens', 'vs', '2026-12-20T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week15'),
  (2026, 15, 'New Orleans Saints', 'Tampa Bay Buccaneers', '@', '2026-12-20T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week15'),
  (2026, 15, 'Tampa Bay Buccaneers', 'New Orleans Saints', 'vs', '2026-12-20T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week15'),
  (2026, 15, 'Indianapolis Colts', 'Tennessee Titans', '@', '2026-12-20T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week15'),
  (2026, 15, 'Tennessee Titans', 'Indianapolis Colts', 'vs', '2026-12-20T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week15'),
  (2026, 15, 'Atlanta Falcons', 'Washington Commanders', '@', '2026-12-20T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week15'),
  (2026, 15, 'Washington Commanders', 'Atlanta Falcons', 'vs', '2026-12-20T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week15'),
  (2026, 15, 'New York Jets', 'Arizona Cardinals', '@', '2026-12-20T21:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week15'),
  (2026, 15, 'Arizona Cardinals', 'New York Jets', 'vs', '2026-12-20T21:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week15'),
  (2026, 15, 'Dallas Cowboys', 'Los Angeles Rams', '@', '2026-12-20T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week15'),
  (2026, 15, 'Los Angeles Rams', 'Dallas Cowboys', 'vs', '2026-12-20T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week15'),
  (2026, 15, 'Denver Broncos', 'Las Vegas Raiders', '@', '2026-12-20T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week15'),
  (2026, 15, 'Las Vegas Raiders', 'Denver Broncos', 'vs', '2026-12-20T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week15'),
  (2026, 15, 'Detroit Lions', 'Minnesota Vikings', '@', '2026-12-21T01:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week15'),
  (2026, 15, 'Minnesota Vikings', 'Detroit Lions', 'vs', '2026-12-21T01:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week15'),
  (2026, 15, 'New England Patriots', 'Kansas City Chiefs', '@', '2026-12-22T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week15'),
  (2026, 15, 'Kansas City Chiefs', 'New England Patriots', 'vs', '2026-12-22T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week15'),
  (2026, 16, 'Houston Texans', 'Philadelphia Eagles', '@', '2026-12-25T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week16'),
  (2026, 16, 'Philadelphia Eagles', 'Houston Texans', 'vs', '2026-12-25T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week16'),
  (2026, 16, 'Green Bay Packers', 'Chicago Bears', '@', '2026-12-25T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week16'),
  (2026, 16, 'Chicago Bears', 'Green Bay Packers', 'vs', '2026-12-25T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week16'),
  (2026, 16, 'Buffalo Bills', 'Denver Broncos', '@', '2026-12-25T21:30:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week16'),
  (2026, 16, 'Denver Broncos', 'Buffalo Bills', 'vs', '2026-12-25T21:30:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week16'),
  (2026, 16, 'Los Angeles Rams', 'Seattle Seahawks', '@', '2026-12-26T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week16'),
  (2026, 16, 'Seattle Seahawks', 'Los Angeles Rams', 'vs', '2026-12-26T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week16'),
  (2026, 16, 'Cleveland Browns', 'Baltimore Ravens', '@', '2026-12-27T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week16'),
  (2026, 16, 'Baltimore Ravens', 'Cleveland Browns', 'vs', '2026-12-27T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week16'),
  (2026, 16, 'Los Angeles Chargers', 'Miami Dolphins', '@', '2026-12-27T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week16'),
  (2026, 16, 'Miami Dolphins', 'Los Angeles Chargers', 'vs', '2026-12-27T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week16'),
  (2026, 16, 'Arizona Cardinals', 'New Orleans Saints', '@', '2026-12-27T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week16'),
  (2026, 16, 'New Orleans Saints', 'Arizona Cardinals', 'vs', '2026-12-27T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week16'),
  (2026, 16, 'New England Patriots', 'New York Jets', '@', '2026-12-27T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week16'),
  (2026, 16, 'New York Jets', 'New England Patriots', 'vs', '2026-12-27T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week16'),
  (2026, 16, 'Tennessee Titans', 'Las Vegas Raiders', '@', '2026-12-27T21:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week16'),
  (2026, 16, 'Las Vegas Raiders', 'Tennessee Titans', 'vs', '2026-12-27T21:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week16'),
  (2026, 16, 'San Francisco 49ers', 'Kansas City Chiefs', '@', '2026-12-27T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week16'),
  (2026, 16, 'Kansas City Chiefs', 'San Francisco 49ers', 'vs', '2026-12-27T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week16'),
  (2026, 16, 'Jacksonville Jaguars', 'Dallas Cowboys', '@', '2026-12-28T01:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week16'),
  (2026, 16, 'Dallas Cowboys', 'Jacksonville Jaguars', 'vs', '2026-12-28T01:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week16'),
  (2026, 16, 'New York Giants', 'Detroit Lions', '@', '2026-12-29T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week16'),
  (2026, 16, 'Detroit Lions', 'New York Giants', 'vs', '2026-12-29T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week16'),
  (2026, 16, 'Tampa Bay Buccaneers', 'Atlanta Falcons', '@', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week16'),
  (2026, 16, 'Atlanta Falcons', 'Tampa Bay Buccaneers', 'vs', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week16'),
  (2026, 16, 'Cincinnati Bengals', 'Indianapolis Colts', '@', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week16'),
  (2026, 16, 'Indianapolis Colts', 'Cincinnati Bengals', 'vs', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week16'),
  (2026, 16, 'Washington Commanders', 'Minnesota Vikings', '@', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week16'),
  (2026, 16, 'Minnesota Vikings', 'Washington Commanders', 'vs', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week16'),
  (2026, 16, 'Carolina Panthers', 'Pittsburgh Steelers', '@', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week16'),
  (2026, 16, 'Pittsburgh Steelers', 'Carolina Panthers', 'vs', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week16'),
  (2026, 17, 'Baltimore Ravens', 'Cincinnati Bengals', '@', '2027-01-01T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week17'),
  (2026, 17, 'Cincinnati Bengals', 'Baltimore Ravens', 'vs', '2027-01-01T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week17'),
  (2026, 17, 'New Orleans Saints', 'Atlanta Falcons', '@', '2027-01-03T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week17'),
  (2026, 17, 'Atlanta Falcons', 'New Orleans Saints', 'vs', '2027-01-03T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week17'),
  (2026, 17, 'Seattle Seahawks', 'Carolina Panthers', '@', '2027-01-03T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week17'),
  (2026, 17, 'Carolina Panthers', 'Seattle Seahawks', 'vs', '2027-01-03T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week17'),
  (2026, 17, 'Indianapolis Colts', 'Cleveland Browns', '@', '2027-01-03T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week17'),
  (2026, 17, 'Cleveland Browns', 'Indianapolis Colts', 'vs', '2027-01-03T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week17'),
  (2026, 17, 'New York Giants', 'Dallas Cowboys', '@', '2027-01-03T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week17'),
  (2026, 17, 'Dallas Cowboys', 'New York Giants', 'vs', '2027-01-03T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week17'),
  (2026, 17, 'Buffalo Bills', 'Miami Dolphins', '@', '2027-01-03T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week17'),
  (2026, 17, 'Miami Dolphins', 'Buffalo Bills', 'vs', '2027-01-03T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week17'),
  (2026, 17, 'Minnesota Vikings', 'New York Jets', '@', '2027-01-03T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week17'),
  (2026, 17, 'New York Jets', 'Minnesota Vikings', 'vs', '2027-01-03T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week17'),
  (2026, 17, 'Pittsburgh Steelers', 'Tennessee Titans', '@', '2027-01-03T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week17'),
  (2026, 17, 'Tennessee Titans', 'Pittsburgh Steelers', 'vs', '2027-01-03T18:00:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week17'),
  (2026, 17, 'Las Vegas Raiders', 'Arizona Cardinals', '@', '2027-01-03T21:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week17'),
  (2026, 17, 'Arizona Cardinals', 'Las Vegas Raiders', 'vs', '2027-01-03T21:05:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week17'),
  (2026, 17, 'Detroit Lions', 'Chicago Bears', '@', '2027-01-03T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week17'),
  (2026, 17, 'Chicago Bears', 'Detroit Lions', 'vs', '2027-01-03T21:25:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week17'),
  (2026, 17, 'Philadelphia Eagles', 'San Francisco 49ers', '@', '2027-01-04T01:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week17'),
  (2026, 17, 'San Francisco 49ers', 'Philadelphia Eagles', 'vs', '2027-01-04T01:20:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week17'),
  (2026, 17, 'Houston Texans', 'Green Bay Packers', '@', '2027-01-05T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week17'),
  (2026, 17, 'Green Bay Packers', 'Houston Texans', 'vs', '2027-01-05T01:15:00Z', false, 'https://plaintextsports.com/nfl/2026/schedule#week17'),
  (2026, 17, 'Washington Commanders', 'Jacksonville Jaguars', '@', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week17'),
  (2026, 17, 'Jacksonville Jaguars', 'Washington Commanders', 'vs', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week17'),
  (2026, 17, 'Kansas City Chiefs', 'Los Angeles Chargers', '@', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week17'),
  (2026, 17, 'Los Angeles Chargers', 'Kansas City Chiefs', 'vs', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week17'),
  (2026, 17, 'Denver Broncos', 'New England Patriots', '@', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week17'),
  (2026, 17, 'New England Patriots', 'Denver Broncos', 'vs', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week17'),
  (2026, 17, 'Los Angeles Rams', 'Tampa Bay Buccaneers', '@', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week17'),
  (2026, 17, 'Tampa Bay Buccaneers', 'Los Angeles Rams', 'vs', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week17'),
  (2026, 18, 'San Francisco 49ers', 'Arizona Cardinals', '@', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week18'),
  (2026, 18, 'Arizona Cardinals', 'San Francisco 49ers', 'vs', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week18'),
  (2026, 18, 'Pittsburgh Steelers', 'Baltimore Ravens', '@', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week18'),
  (2026, 18, 'Baltimore Ravens', 'Pittsburgh Steelers', 'vs', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week18'),
  (2026, 18, 'New York Jets', 'Buffalo Bills', '@', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week18'),
  (2026, 18, 'Buffalo Bills', 'New York Jets', 'vs', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week18'),
  (2026, 18, 'Atlanta Falcons', 'Carolina Panthers', '@', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week18'),
  (2026, 18, 'Carolina Panthers', 'Atlanta Falcons', 'vs', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week18'),
  (2026, 18, 'Cleveland Browns', 'Cincinnati Bengals', '@', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week18'),
  (2026, 18, 'Cincinnati Bengals', 'Cleveland Browns', 'vs', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week18'),
  (2026, 18, 'Los Angeles Chargers', 'Denver Broncos', '@', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week18'),
  (2026, 18, 'Denver Broncos', 'Los Angeles Chargers', 'vs', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week18'),
  (2026, 18, 'Detroit Lions', 'Green Bay Packers', '@', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week18'),
  (2026, 18, 'Green Bay Packers', 'Detroit Lions', 'vs', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week18'),
  (2026, 18, 'Tennessee Titans', 'Houston Texans', '@', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week18'),
  (2026, 18, 'Houston Texans', 'Tennessee Titans', 'vs', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week18'),
  (2026, 18, 'Jacksonville Jaguars', 'Indianapolis Colts', '@', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week18'),
  (2026, 18, 'Indianapolis Colts', 'Jacksonville Jaguars', 'vs', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week18'),
  (2026, 18, 'Las Vegas Raiders', 'Kansas City Chiefs', '@', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week18'),
  (2026, 18, 'Kansas City Chiefs', 'Las Vegas Raiders', 'vs', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week18'),
  (2026, 18, 'Seattle Seahawks', 'Los Angeles Rams', '@', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week18'),
  (2026, 18, 'Los Angeles Rams', 'Seattle Seahawks', 'vs', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week18'),
  (2026, 18, 'Chicago Bears', 'Minnesota Vikings', '@', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week18'),
  (2026, 18, 'Minnesota Vikings', 'Chicago Bears', 'vs', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week18'),
  (2026, 18, 'Miami Dolphins', 'New England Patriots', '@', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week18'),
  (2026, 18, 'New England Patriots', 'Miami Dolphins', 'vs', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week18'),
  (2026, 18, 'Tampa Bay Buccaneers', 'New Orleans Saints', '@', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week18'),
  (2026, 18, 'New Orleans Saints', 'Tampa Bay Buccaneers', 'vs', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week18'),
  (2026, 18, 'Philadelphia Eagles', 'New York Giants', '@', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week18'),
  (2026, 18, 'New York Giants', 'Philadelphia Eagles', 'vs', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week18'),
  (2026, 18, 'Dallas Cowboys', 'Washington Commanders', '@', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week18'),
  (2026, 18, 'Washington Commanders', 'Dallas Cowboys', 'vs', null, true, 'https://plaintextsports.com/nfl/2026/schedule#week18')
on conflict (season, week, team) do update set
  opponent = excluded.opponent,
  home_away = excluded.home_away,
  kickoff_at_utc = excluded.kickoff_at_utc,
  is_tbd = excluded.is_tbd,
  source_url = excluded.source_url;

create or replace function public.ff_apply_pick_schedule()
returns trigger
language plpgsql
as $$
declare
  schedule_row public.ff_nfl_schedule%rowtype;
  current_pick_team text;
  current_pick_schedule public.ff_nfl_schedule%rowtype;
begin
  if new.season is null then
    new.season := 2026;
  end if;

  if new.submitted_at_utc is null then
    new.submitted_at_utc := now();
  end if;

  if new.result is null then
    new.result := 'SUSPECT';
  end if;

  select * into schedule_row
  from public.ff_nfl_schedule
  where season = new.season
    and week = new.week
    and team = new.team;

  if not found then
    raise exception 'No scheduled NFL game found for % in Week %', new.team, new.week;
  end if;

  if schedule_row.kickoff_at_utc is not null
     and now() >= schedule_row.kickoff_at_utc - interval '2 minutes' then
    raise exception 'Pick window closed for % in Week %', new.team, new.week;
  end if;

  select latest_pick.team into current_pick_team
  from (
    select team
    from public.ff_picks
    where user_id = new.user_id
      and season = new.season
      and week = new.week
    order by submitted_at_utc desc, created_at desc
    limit 1
  ) latest_pick;

  if current_pick_team is not null and current_pick_team <> new.team then
    select * into current_pick_schedule
    from public.ff_nfl_schedule
    where season = new.season
      and week = new.week
      and team = current_pick_team;

    if found
       and current_pick_schedule.kickoff_at_utc is not null
       and now() >= current_pick_schedule.kickoff_at_utc - interval '2 minutes' then
      raise exception 'Week % is locked because % already reached its pick window', new.week, current_pick_team;
    end if;
  end if;

  if exists (
    select 1
    from (
      select distinct on (week) week, team
      from public.ff_picks
      where user_id = new.user_id
        and season = new.season
        and week <> new.week
      order by week, submitted_at_utc desc, created_at desc
    ) latest_by_week
    where latest_by_week.team = new.team
  ) then
    raise exception '% has already been named in another week', new.team;
  end if;

  new.opponent := schedule_row.opponent;
  new.home_away := schedule_row.home_away;
  new.kickoff_at_utc := schedule_row.kickoff_at_utc;
  new.schedule_source_url := schedule_row.source_url;
  return new;
end;
$$;

drop trigger if exists ff_apply_pick_schedule_before_insert on public.ff_picks;
create trigger ff_apply_pick_schedule_before_insert
before insert on public.ff_picks
for each row
execute function public.ff_apply_pick_schedule();

create or replace view public.ff_active_picks as
select distinct on (user_id, season, week) *
from public.ff_picks
order by user_id, season, week, submitted_at_utc desc, created_at desc;

create or replace view public.ff_current_suspects as
select
  profiles.id,
  profiles.username,
  profiles.first_name,
  profiles.avatar_data_url,
  coalesce(latest_pick.result, 'SUSPECT') as game_status
from public.ff_profiles as profiles
left join lateral (
  select active_picks.result
  from public.ff_active_picks as active_picks
  where active_picks.user_id = profiles.id
  order by active_picks.week desc, active_picks.submitted_at_utc desc, active_picks.created_at desc
  limit 1
) as latest_pick on true
order by profiles.username;

grant select on public.ff_nfl_schedule to anon, authenticated;
grant select on public.ff_active_picks to anon, authenticated;
revoke all on public.ff_current_suspects from anon, authenticated;
grant select (id, username, avatar_data_url, game_status)
  on public.ff_current_suspects to anon;
grant select on public.ff_current_suspects to authenticated;
